# Site Settings
title: Xuexue's Blog
description: Personal blog of aireet
author: Xuexue
email: xuexuexue_xxx@proton.me

# URL Settings
baseurl: "/aireet"
url: "https://aireet.github.io"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .gitignore
  - README.md
  - CLAUDE.md

# Posts Settings
post_defaults:
  layout: post
